version: '3'
services:
  app:
    container_name: app-workast
    build: .
    ports:
      - '8080:8080'
    restart: always
    environment:
     - NODE_ENV=production
     - MONGODB_URL=mongodb://mongo:27017/workast
     - AUTH_TOKEN=5CD4ED173E1C95FE763B753A297D5
     - PORT=8080
    links:
      - mongo
  mongo:
    container_name: mongo-workast
    image: mongo
    ports:
      - '27017:27017'
